{
 "title": "Request Statistics Demo",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Requests Handled Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests / second" }
   ],
   "targets": [
    { "expr": "irate(rpc_reqs_count [60s])" }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(rpc_durations_histogram_seconds_sum[30s])/rate(rpc_durations_histogram_seconds_count[30s])"
    }
   ]
  },
  {
   "title": "Latency Histogram Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "irate(rpc_durations_histogram_seconds_bucket [60s])",
     "legendFormat": "{{le}} ms"
    }
   ]
  }
 ]
}